### ISSUE TITLE
Compute TI, l from spectra or Reynolds Stress and validate

### ISSUE THREAD

**Issue by thclark** [octue/es-flow#37]
By integrating the spectra, or from the Reynolds Stresses (if possible?) compute Turbulent Intensity and lengthscale values.

These can be used in existing analysis codes to generate turbulent fields with the Mann method and TurbSim (using von Karman or Kaimal approximations until a field generator can be added to es-flow which properly reflects spectral shape).

## Tasks
- [ ] Add function stub `get_ti` to `adem.h` (either a member function to AdemData or an extra function depending on whether #34 is done)

- [ ] Use that function to compute TI and lengthscale (directional parameters), suitable for use in turbsim. Add the output profiles of `TI_i`, `l_ij` to AdemData.

- [ ] Create a `relations/spectra.h` module to enable us to get spectra at a given height or heights, given known input parameters.

- [ ] Add a von karman spectrum generator in `relations/spectra.h`

- [ ] Add a kaimal spectrum generator in `relations/spectra.h`

- [ ] Add an adem spectrum generator in `relations/spectra.h` which will work slightly differently (it'll call `adem()` instead of directly compute)

## Validation
In processes using `adem`, it'll be possible to take the output values and, for given heights, generate ADEM, Kaimal and von Karman spectra, with consistent TI and L values across the board.

Determine a value of 'goodness' for Kaimal and von Karman, comparing their analytical solutions to the smooth analytical ADEM spectrum. This tells you which one better represents the actual spectrum through the boundary layer.
